blueprint:
  name: Voice - Perform YouTube Search
  author: luuquangvu
  source_url: https://github.com/luuquangvu/tutorials/blob/dev/advanced_youtube_search_full_llm.yaml
  description: |-
    # Tool for searching YouTube videos used for Voice Assistant

    ## Blueprint Setup

    ### Required

    - The Pyscript integration needs to be installed through HACS and properly configured.
    - The `scripts/youtube_data_tool.py` script needs to be copied into the `config/pyscript` folder.
    - The `scripts/requirements.txt` file needs to be copied into the `config/pyscript` folder.
    - The mentioned file(s) is/are included in the repository.
    - You need to enable two Pyscript options through the UI or via YAML to allow importing all Python packages and to make hass available as a global variable.
    - A YouTube API key needs to be configured in `config/configuration.yaml` and `config/secrets.yaml`.

    ```
    # File configuration.yaml
    pyscript:
      allow_all_imports: true
      hass_is_global: true
      youtube_api_key: !secret youtube_api_key
    ```

    ```
    # File secrets.yaml
    youtube_api_key: XXXXXX     # Retrieve the key from the Google Cloud Console.
    ```

    ### Optional

    - Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    - The `play_youtube_video_full_llm.yaml` blueprint needs to be installed to play YouTube videos on a smart TV.
    - Provide a concise and precise description for the script. This description will enable the LLM to recognize that the script is designed to search videos from YouTube.
    - Make sure to expose the script to Assist after the script has been saved.
    - Do not alter the default script name.
    - Once the script is created, click the three dots in the top right corner, choose "Edit in YAML," and remove the `description: ...` line to restore the default. This step is important because it helps the LLM better understand the script's purpose.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    results_settings:
      name: Settings for Results
      icon: mdi:youtube
      description: These settings allow you to define the maximum number of results that will return for each request.
      collapsed: true
      input:
        results:
          name: Number Of Results
          selector:
            number:
              min: 0
              max: 50
              step: 1
          default: 5
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        query_string_prompt:
          name: Query String Prompt
          description: The prompt which will be used for the LLM can provide the search string for the query.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. Search query. Silence-correct misspellings. For results, use ordinal numbers for selection; omit Media IDs. Confirm before proceeding if query is ambiguous.
        page_token_prompt:
          name: Page Token Prompt
          description: The prompt which will be used for the LLM can provide the page token to get additional videos that could be obtained.
          selector:
            text:
              multiline: true
          default: |-
            Optional. Use to fetch more videos if initial results are unsatisfactory.
mode: parallel
max_exceeded: silent
description: Searches YouTube for videos and returns a list of matching results with titles and descriptions. Use to find specific content or playlists.
variables:
  version: 20260207
fields:
  query_string:
    name: Query String
    description: !input query_string_prompt
    selector:
      text:
    required: true
  page_token:
    name: Page Token
    description: !input page_token_prompt
    selector:
      text:
sequence:
  - variables:
      results: !input results
      query_string: "{{ query_string | default('') | trim }}"
      page_token: "{{ page_token | default('') | trim }}"
  - alias: Check if variables were set correctly
    if:
      - condition: template
        value_template: "{{ not query_string }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: Unable to search for videos because the query string is empty.
      - alias: Stop the script
        stop: Unable to search for videos because the query string is empty.
        response_variable: response
  - action: pyscript.youtube_search_tool
    response_variable: response
    data:
      query: "{{ query_string }}"
      search_type: "video"
      results: "{{ results }}"
      page_token: "{{ page_token }}"
  - if:
      - condition: template
        value_template: "{{ response.get('error') }}"
    then:
      - variables:
          response:
            error: "{{ response.error }}"
    else:
      - variables:
          response:
            entries: |-
              {% for entry in response.get('items') if entry.id.kind == 'youtube#video' -%}
              - channel: {{ entry.snippet.channelTitle | lower }}
                title: {{ entry.snippet.title | lower }}
                published: {{ strptime(entry.snippet.publishedAt, '%Y-%m-%dT%H:%M:%S%z') | relative_time }} ago
                media_id: {{ entry.id.videoId }}
              {% endfor -%}
            next_page_token: "{{ response.get('nextPageToken') }}"
  - stop: ""
    response_variable: response
