blueprint:
  name: Voice - Get Calendar Events
  author: luuquangvu
  source_url: https://github.com/luuquangvu/tutorials/blob/main/calendar_events_lookup_full_llm.yaml
  description: |-
    # Tool gets events from calendar used for Voice Assistant

    ## Blueprint Setup

    ### Required

    - Set one or more calendar entities for which you want to get the events.

    ### Optional

    - Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    - Provide a concise and precise description for the script. This script will be utilized by the LLM to understand that it should obtain events from the specified calendars.
    - Make sure to expose the script to Assist after the script has been saved.
    - Do not alter the default script name.
    - Once the script is created, click the three dots in the top right corner, choose "Edit in YAML," and remove the `description: ...` line to restore the default. This step is important because it helps the LLM better understand the script's purpose.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    calendar_settings:
      name: Settings for Calendar
      icon: mdi:calendar
      description: You can use these settings to configure Calendar entities.
      input:
        calendar_entities:
          name: Calendar Entities
          description: Select the calendar entities to fetch the events from.
          selector:
            entity:
              filter:
                domain: calendar
              multiple: true
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        time_period_type_prompt:
          name: Time Period Type Prompt
          description: The prompt which will be used for the LLM can provide the type for the period (days or hours).
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. 'daily' for full days/long periods; 'hourly' for partial days/specific times. Response must only include day of week and start date.
        time_period_length_prompt:
          name: Time Period Length Prompt
          description: The prompt which will be used for the LLM can provide the length of the period.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. Length in days (if daily) or hours (if hourly). E.g. 1 (today), 7 (week), 6 (afternoon).
        date_prompt:
          name: Date Prompt
          description: The prompt which will be used for the LLM can provide the start date for the events period.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. Start date (YYYY-MM-DD). Default to today if unspecified. For "night", use next day unless current time < 05:00:00.
        time_prompt:
          name: Time Prompt
          description: The prompt which will be used for the LLM can provide the start time for the events period.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. Start time (HH:MM:SS). Full day = 00:00:00. Morning = 06:00:00, Afternoon = 12:00:00, Evening = 18:00:00, Night = 00:00:00.
mode: parallel
max_exceeded: silent
description: Retrieves upcoming or past calendar events for a specific time period. Useful for checking schedules and appointments.
variables:
  version: 20260222
fields:
  time_period_type:
    name: Time Period Type
    description: !input time_period_type_prompt
    selector:
      select:
        options:
          - daily
          - hourly
    required: true
  time_period_length:
    name: Time Period Length
    description: !input time_period_length_prompt
    selector:
      number:
        min: 1
        max: 120
    required: true
  start_date:
    name: Start Date
    description: !input date_prompt
    selector:
      date:
    required: true
  start_time:
    name: Start Time
    description: !input time_prompt
    selector:
      time:
    required: true
sequence:
  - variables:
      start_date: "{{ start_date | as_datetime(default='') }}"
      start_time: "{{ start_time | default('00:00:00') | as_timedelta | default('00:00:00', true) }}"
      start: >-
        {{ ((start_date | as_datetime + as_timedelta(start_time)) | as_local) if start_date else 'n/a' }}
      end: >-
        {% if start != 'n/a' %}
        {% set start = as_datetime(start) %}
        {% set add = (time_period_length | default(1) | float(1)) | abs %}
        {% set type = time_period_type if (time_period_type | default) in ['daily', 'hourly'] else 'daily' %}
        {{ (start + timedelta(days = add if type == 'daily' else 0, hours = add if type == 'hourly' else 0)) | as_local }}
        {% endif %}
  - alias: Check if variables were set correctly
    if:
      - condition: template
        value_template: "{{ start == 'n/a' or end | as_datetime < now() }}"
    then:
      - alias: Set variable for eror message
        variables:
          response:
            error: Unable to provide calendar events as the start date is either empty or in the past.
      - alias: Stop the script
        stop: Unable to provide calendar events as the start date is either empty or in the past.
        response_variable: response
  - action: calendar.get_events
    target:
      entity_id: !input calendar_entities
    response_variable: response
    data:
      start_date_time: "{{ start }}"
      end_date_time: "{{ end }}"
  - variables:
      response:
        events: >-
          {{
            response.values()
              | map(attribute='events')
              | sum(start=[])
              | sort(attribute='start')
          }}
  - stop: ""
    response_variable: response
