blueprint:
  name: Voice - Convert Calendar Dates
  author: luuquangvu
  source_url: https://github.com/luuquangvu/tutorials/blob/dev/date_lookup_and_conversion_full_llm.yaml
  description: |-
    # Tool converts Solar date to Lunar date and vice versa used for Voice Assistant

    ## Blueprint Setup

    ### Required

    - The Pyscript integration needs to be installed through HACS and properly configured.
    - The `scripts/date_conversion_tool.py` script needs to be copied into the `config/pyscript` folder.
    - The mentioned file(s) is/are included in the repository.
    - You need to enable two Pyscript options through the UI or via YAML to allow importing all Python packages and to make hass available as a global variable.

    ```
    # File configuration.yaml
    pyscript:
      allow_all_imports: true
      hass_is_global: true
    ```

    ### Optional

    - Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    - Provide a concise and precise description for the script. This will be utilized by the LLM to understand it should use this script for date conversion from Solar date to Lunar date and vice versa.
    - Make sure to expose the script to Assist after the script has been saved.
    - Do not alter the default script name.
    - Once the script is created, click the three dots in the top right corner, choose "Edit in YAML," and remove the `description: ...` line to restore the default. This step is important because it helps the LLM better understand the script's purpose.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        conversion_type_prompt:
          name: Conversion Type Prompt
          description: The prompt which will be used for the LLM can provide the type for the conversion.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. 's2l' (Solar to Lunar) or 'l2s' (Lunar to Solar). Response must include: day of week, both dates, and days remaining/elapsed.
        date_prompt:
          name: Date Prompt
          description: The prompt which will be used for the LLM can provide the input date for the conversion.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. Date (YYYY-MM-DD). If year unspecified, use current year. Use today/tomorrow as needed.
        leap_month_prompt:
          name: Leap Month Prompt
          description: The prompt which will be used for the LLM can provide the leap month for the conversion.
          selector:
            text:
              multiline: true
          default: |-
            Optional for l2s. 'true' for leap month, 'false' for regular. Do not use for s2l.
mode: parallel
max_exceeded: silent
description: Converts dates between Solar and Lunar calendars, looks up auspicious days, and determines the day of the week.
variables:
  version: 20260207
fields:
  conversion_type:
    name: Conversion Type
    description: !input conversion_type_prompt
    selector:
      select:
        options:
          - s2l
          - l2s
    required: true
  date:
    name: Date
    description: !input date_prompt
    selector:
      date:
    required: true
  leap_month:
    name: Leap Month
    description: !input leap_month_prompt
    selector:
      boolean:
sequence:
  - variables:
      conversion_type: "{{ conversion_type | default('') | trim }}"
      date: "{{ (date | as_datetime(default=now())).date() }}"
      leap_month: "{{ leap_month | default(false) }}"
  - alias: Check if variables were set correctly
    if:
      - condition: template
        value_template: "{{ not (conversion_type in ['s2l', 'l2s']) }}"
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: Unable to perform the date conversion because the conversion type is invalid.
      - alias: Stop the script
        stop: Unable to perform the date conversion because the conversion type is invalid.
        response_variable: response
  - action: pyscript.date_conversion_tool
    response_variable: response
    data:
      conversion_type: "{{ conversion_type }}"
      date: "{{ date }}"
      leap_month: "{{ leap_month }}"
  - stop: ""
    response_variable: response
