blueprint:
  name: Voice - Set Fan Oscillation
  author: luuquangvu
  source_url: https://github.com/luuquangvu/tutorials/blob/dev/fan_oscillation_control_full_llm.yaml
  description: |-
    # Tool for Controlling Fan Oscillation used for Voice Assistant

    ## Blueprint Setup

    ### Required

    - A smart fan integrated into Home Assistant.
    - A template sensor stores all information about entity aliases needs to be configured in `config/configuration.yaml`; The sensor is required for friendly-name lookup.

    ```
    # File configuration.yaml
    shell_command:
      get_entity_alias: jq '[.data.entities[] | select(.options.conversation.should_expose == true and (.aliases | length > 0)) | {entity_id, aliases}]' ./.storage/core.entity_registry
    template:
      - triggers:
          - trigger: homeassistant
            event: start
          - trigger: event
            event_type: event_template_reloaded
        actions:
          - action: shell_command.get_entity_alias
            response_variable: response
        sensor:
          - name: "Assist: Entity IDs and Aliases"
            unique_id: entity_ids_and_aliases
            icon: mdi:format-list-bulleted
            device_class: timestamp
            state: "{{ now().isoformat() }}"
            attributes:
              entities: "{{ response.stdout }}"
    ```

    ### Optional

    - Adjust the prompts for each field used in the script. The descriptions guide the LLM to provide the correct input.

    ### Note

    - Provide a concise and precise description for the script. This will be utilized by the LLM to understand it should use this script for controlling oscillation of a smart fan.
    - Make sure to expose the fan entities you want to control to Assist.
    - Make sure to expose the script to Assist after the script has been saved.
    - Do not alter the default script name.
    - Once the script is created, click the three dots in the top right corner, choose "Edit in YAML," and remove the `description: ...` line to restore the default. This step is important because it helps the LLM better understand the script's purpose.
  domain: script
  homeassistant:
    min_version: 2024.10.0
  input:
    entity_aliases_settings:
      name: Settings for Entity Aliases
      icon: mdi:format-list-bulleted
      description: You can use these settings to configure a template sensor that stores all information about entity aliases.
      input:
        entity_aliases:
          name: Entity Aliases
          selector:
            entity:
              filter:
                - domain: sensor
                  integration: template
    prompt_settings:
      name: Prompt settings for the LLM
      icon: mdi:robot
      description: You can use these settings to finetune the prompts for your specific LLM (model). In most cases the defaults should be fine.
      collapsed: true
      input:
        fan_entities_prompt:
          name: Fan Entities Prompt
          description: The prompt which will be used for the LLM can provide the name of fans for controlling.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. Provide fan names to control. Use semicolons (;) to separate multiple names.
        oscillating_prompt:
          name: Oscillating Prompt
          description: The prompt which will be used for the LLM can provide the oscillation state.
          selector:
            text:
              multiline: true
          default: |-
            Mandatory. Set oscillation: 'true' (ON), 'false' (OFF). Do not guess.
mode: parallel
max_exceeded: silent
description: Simple fan oscillation control (on/off) for specified fan entities.
variables:
  version: 20260207
fields:
  fan_entities:
    name: Fan Entities
    description: !input fan_entities_prompt
    selector:
      text:
    required: true
  oscillating:
    name: Oscillating
    description: !input oscillating_prompt
    selector:
      boolean:
    required: true
sequence:
  - variables:
      entity_aliases: !input entity_aliases
      fan_entities: "{{ fan_entities | default('') | trim }}"
      oscillating: "{{ oscillating | default(false) }}"
  - alias: Check if variables were set correctly
    if:
      - condition: template
        value_template: >-
          {% set validation = namespace(not_exist=false) -%}
          {% for entity in fan_entities.split(';') -%}
          {% if not ((states.fan | selectattr('attributes.friendly_name', 'eq', entity.strip()) | list) or
          (state_attr(entity_aliases, 'entities') | default([]) | selectattr('entity_id', 'match', 'fan\.') | selectattr('aliases', 'contains', entity.strip()) | list)) -%}
          {% set validation.not_exist = true -%}
          {% endif -%}
          {% endfor -%}
          {{ validation.not_exist }}
    then:
      - alias: Set variable for error message
        variables:
          response:
            error: Unable to control the fan because the fan name is invalid.
      - alias: Stop the script
        stop: Unable to control the fan because the fan name is invalid.
        response_variable: response
  - variables:
      devices: >-
        {% set device = namespace(entities=[]) -%}
        {% for entity in fan_entities.split(';') -%}
        {% if (states.fan | selectattr('attributes.friendly_name', 'eq', entity.strip()) | list) -%}
        {% set device.entities = device.entities + (states.fan | selectattr('attributes.friendly_name', 'eq', entity.strip()) | map(attribute='entity_id') | list) -%}
        {% else -%}
        {% set device.entities = device.entities + (state_attr(entity_aliases, 'entities') | default([]) | selectattr('entity_id', 'match', 'fan\.') | selectattr('aliases', 'contains', entity.strip()) | map(attribute='entity_id') | list) -%}
        {% endif -%}
        {% endfor -%}
        {{ device.entities }}
  - variables:
      friendly_fans: >-
        {% set names = namespace(values=[]) -%}
        {% for name in fan_entities.split(';') -%}
        {% if name | trim -%}
        {% set names.values = names.values + [name.strip()] -%}
        {% endif -%}
        {% endfor -%}
        {{ names.values }}
  - action: fan.oscillate
    target:
      entity_id: "{{ devices | join(', ') }}"
    data:
      oscillating: "{{ (oscillating | string) | lower }}"
  - alias: Prepare success response for Assist
    variables:
      response:
        success: >-
          Turned {{ 'on' if oscillating else 'off' }} oscillation for {{
          friendly_fans | join(', ') }}.
  - stop: Finish and return response data
    response_variable: response
