blueprint:
  name: Link On/Off State of Multiple Devices
  author: luuquangvu
  source_url: https://github.com/luuquangvu/tutorials/blob/dev/link_multiple_devices.yaml
  description: |-
    # Link State of Multiple Devices (Ultra-Fast)

    Synchronize On/Off states across multiple entities instantly. If one device is toggled, others follow.

    ### Key Features:
    - **Smart Sync:** Only sends commands to devices that need a state change, preventing infinite loops and network congestion.
    - **Ultra-Fast Performance:** Optimized using direct string-based filtering for near-zero latency.
    - **Fail-Safe:** Automatically excludes the trigger entity and ignores `unavailable/unknown` devices to prevent execution errors and keep system logs clean.

    ### Requirements:
    - Entities must support `homeassistant.turn_on` and `homeassistant.turn_off`.
    - Requires Home Assistant 2024.10.0 or newer.
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input:
    linked_entities:
      name: Entities
      description: Entities to link together
      selector:
        entity:
          multiple: true
mode: parallel
max_exceeded: silent
variables:
  version: 20251223
  linked_entities: !input linked_entities
triggers:
  - trigger: state
    entity_id: !input linked_entities
    from:
      - "on"
      - "off"
    to:
      - "off"
      - "on"
actions:
  - variables:
      target_entities: >-
        {{ linked_entities
           | reject('eq', trigger.entity_id)
           | select('is_state', 'off' if trigger.to_state.state == 'on' else 'on')
           | list }}
  - condition: template
    value_template: "{{ target_entities | length > 0 }}"
  - action: "homeassistant.turn_{{ trigger.to_state.state }}"
    target:
      entity_id: "{{ target_entities }}"
